---
services:
  postgres:
    image: postgres
    container_name: locks-db
    ports:
      - "7432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: ["postgres", "-c", "log_statement=all"]
